layout_spectrum: 0.4679595
color:
  saturation: 0
  brandStrength: 0.4147721
  lightness: 1
  rhythmicContrast: 0
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.5590219
name: kwei
